### ISSUE TITLE
Balance endless mode earnings

### ISSUE THREAD

**Issue by elinicksic** [thebclickteam/bocracy#103]
The series mode earnings are way too much and the price is way to easy. I got 2500 and only used 1 character and paid 27 redbacks.

Maybe there could be a max of 500 earnings which makes sense and will stop people from getting so much. Or the max could be a factor of the cost (27 cost * 20 = 540 max earnings).

**Comment by elinicksic** [comment]
And/or the cost could be more

**Comment by ghost** [comment]
I really love this idea. I agree to raise the price to pay for series mode (now endless mode). This will be smart to do so not every will do it.

Plus, making a max earnings is better than lowering the earnings. I like your formula for setting the max and I agree to have it somewhere around 500. Then only problem is, is that 500 would be for 1 character. So I think it should be *5 instead of *20 (making 1 character be 125, 2 be 250).

But if we change it to *5, I think we should lower the price to play.

So nice summary, we should keep he same price, but set a max earnings based off of cost * 5.

What about this, @ethanchoo?

**Comment by ethanchoo** [comment]
I think the new price is fine, and the max should be good enough.

**Comment by ghost** [comment]
So you are saying what? Both, none? Sorry

**Comment by ethanchoo** [comment]
Both

**Comment by ghost** [comment]
Ah! Ok. So if we do both, I think the price should be double (27 for archer —> 54) and the earnings should then be *5 the cost (archer 54 * 5 = 270). So this means that it will be harder to play endless mode and you can only profit a max of 4 times your cost. And I think they will earn the max really easily but at least you can’t get more earnings, but you can at least play more (to make it more fun).

Thanks @ethanchoo and @dolphinbob for your wonderful help!

**Comment by ghost** [comment]
Also think of it as, you can unlock a character (goblin) by playing series mode once with these new changes.

**Comment by VishwamR** [comment]
What if endless mode was like the hardcore mode of the game

**Comment by ghost** [comment]
That's what we were originally going to do, but having it where you must select characters doesn't make a good user experience because the user has to take time AND understand to play endless mode. That is why we added the big play button to quickly play, so there could be a better user experience.

But thanks for the suggestion, as I also originally thought that was a great idea.

**Comment by ghost** [comment]
I resolved this issue, but I did a different approach which I think is better and is definitely less code. All I did was make a maximum amount you can earn.

This is better because not only does it use less code, but it also is good no matter how much characters you are using. If you have one character, good, you played hard. If you had a lot, good, you didn't get an insane amount, the game is still fun and challenging.
