### ISSUE TITLE
Change Batalifor General name

### ISSUE THREAD

**Issue by VishwamR** [thebclickteam/bocracy#165]
I feel like we should change the name of the batalifor general to batalifor captain because general is an extremely high ranking and it should be reserved for a boss

**Comment by ghost** [comment]
Yes, that is a great idea! We could have the current "Batalifor General" be the "Batalifor Captain" and then create a "Batalifor General" or something for one of the boss battlegrounds.

We can look in to this, @ethanchoo what do you say?

**Comment by VishwamR** [comment]
I have the general and the background finished. The background is a
laboratory.

>

**Comment by ghost** [comment]
The laboratory background I think should be a different battleground. But the new batalifor general looks great!

But do you think we should name it the "Batalifor Alpha" and then the current general could still be the "Batalifor Captain"?

Because I associate a general as very similar to a captain, but the images look  completely different. The new one looks more like the alpha (the leader of everything). What do you think?

**Comment by VishwamR** [comment]
I think we should keep it as a general and the alpha should be a giant robot

>

**Comment by ghost** [comment]
Yes, that is good. Now that we will have another character that is better than the new general, you can do what you just said.
