### ISSUE TITLE
Remove Kiip and use Google Adsense

### ISSUE THREAD

**Issue by ghost** [thebclickteam/bocracy#40]
This will let the battling not interrupt in the middle of a battle and it will give us more revenue.

We can use the Google Adsense display ads (1) or page level interstitial ads (2).

1. This can show in between each battle
2. This can show in between each page load

This will require:
- Not getting banned from Google Adsense. The first time we used Google Adsense, we got a violation because someone was clicking over and over again.

**Comment by ghost** [comment]
Removed Kiip in commit 2442f44

**Comment by faithtsang** [comment]
Wait a second though. Didn't you want us to click ads over and over again since it gave you 18 cents a click. The frequent clicker wasn't me although I thought clicking over and over again was a good thing. How can you get a violation for that? It shows that we're aware of customer's interests and we are able to show them relevant ads every single time.

**Comment by CameronSamuels** [comment]
I never said that. I didn't want us to get violated.

**Comment by ghost** [comment]
I actually think we should just not use Google Adsense display ads and just use video ads.
