### ISSUE TITLE
Characters are missing

### ISSUE THREAD

**Issue by CooperLan** [thebclickteam/bocracy#42]
Characters dont appear on store or battle mode.

**Comment by ghost** [comment]
They are appearing for me. Upload a screenshot to this issue.

This might be that your device is not displaying non https images because of cross origin policy. But if it is because of this, all the other images (like backgrounds or back buttons, etc) won’t appear either.

![store works](https://user-images.githubusercontent.com/25394678/29237385-dd8bbadc-7ee2-11e7-9696-067a018f7231.png)
![battle works](https://user-images.githubusercontent.com/25394678/29237386-dd9e02aa-7ee2-11e7-84b8-b94a8ddc7404.png)
![series mode selection works](https://user-images.githubusercontent.com/25394678/29237389-f5189f4e-7ee2-11e7-9853-0924ea620dff.png)

**Comment by CooperLan** [comment]
How do I post screenshots

**Comment by CameronSamuels** [comment]
Post them on slack.

**Comment by ghost** [comment]
@CooperLan, is this on the Android app's offline version?

**Comment by ghost** [comment]
I haven't gotten a response for this question so I will close this issue for now. Please still respond once you have a chance.

**Comment by ghost** [comment]
@CooperLan, also, don't assign people to issues, let me do that because I will only have it assigned to a person currently working on that issue.
